version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    labels:
      - bot:dependabot
      - type:chore
      - area:github
    open-pull-requests-limit: 5
    groups:
      github-actions-safe:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
