use anyhow::Context;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

pub fn service_new(octon_dir: &Path, category: &str, name: &str) -> anyhow::Result<()> {
    validate_ident(category)?;
    validate_ident(name)?;

    let services_root = octon_dir
        .join("capabilities")
        .join("runtime")
        .join("services");
    let service_dir = services_root.join(category).join(name);
    let rust_dir = service_dir.join("rust");
    let rust_src = rust_dir.join("src");
    let rust_wit = rust_dir.join("wit");

    std::fs::create_dir_all(&rust_src)
        .with_context(|| format!("create {}", rust_src.display()))?;
    std::fs::create_dir_all(&rust_wit)
        .with_context(|| format!("create {}", rust_wit.display()))?;

    // Copy canonical WIT world.
    let world_src = octon_dir
        .join("engine")
        .join("runtime")
        .join("wit")
        .join("world.wit");
    let world_dst = rust_wit.join("world.wit");
    if world_src.is_file() {
        std::fs::copy(&world_src, &world_dst)
            .with_context(|| format!("copy {} -> {}", world_src.display(), world_dst.display()))?;
    }

    let crate_name = format!("octon-{}-{}-service", category, name);

    let cargo_toml = format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.26"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

[package.metadata.component]
package = "octon:runtime"

[package.metadata.component.target]
world = "octon-service"
"#
    );

    std::fs::write(rust_dir.join("Cargo.toml"), cargo_toml)
        .with_context(|| "write Cargo.toml")?;

    let lib_rs = r#"use serde::{Deserialize, Serialize};

#[allow(warnings)]
mod bindings;
use bindings::Guest;

#[derive(Default)]
pub struct Service;

#[derive(Debug, Deserialize)]
struct PingInput {
    #[serde(default)]
    message: Option<String>,
}

#[derive(Debug, Serialize)]
struct PingOutput {
    ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    message: Option<String>,
}

impl bindings::Guest for Service {
    fn invoke(op: String, input_json: String) -> String {
        match op.as_str() {
            "ping" => {
                let input: PingInput = serde_json::from_str(&input_json).unwrap_or(PingInput { message: None });
                let out = PingOutput { ok: true, message: input.message };
                serde_json::to_string(&out).unwrap()
            }
            _ => {
                // The kernel should reject unknown ops before invoking.
                panic!("unknown op: {}", op);
            }
        }
    }
}

bindings::export!(Service with_types_in bindings);
"#;

    std::fs::write(rust_src.join("lib.rs"), lib_rs).with_context(|| "write src/lib.rs")?;

    // service.json template.
    let service_json = serde_json::json!({
        "format_version": "service-manifest-v1",
        "name": name,
        "version": "0.1.0",
        "category": category,
        "abi": "octon-service@1.0.0",
        "entry": "service.wasm",
        "capabilities_required": ["log.write"],
        "ops": {
            "ping": {
                "input_schema": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {"message": {"type": "string"}}
                },
                "output_schema": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["ok"],
                    "properties": {
                        "ok": {"type": "boolean"},
                        "message": {"type": "string"}
                    }
                }
            }
        },
        "limits": {
            "max_request_bytes": 1048576,
            "max_response_bytes": 1048576,
            "timeout_ms": 5000,
            "max_concurrency": 4
        },
        "docs": {
            "summary": "Template service",
            "help": "Generated by `octon service new`"
        }
    });

    std::fs::write(
        service_dir.join("service.json"),
        serde_json::to_vec_pretty(&service_json)?,
    )
    .with_context(|| "write service.json")?;

    // Create placeholder entry file.
    let entry_path = service_dir.join("service.wasm");
    if !entry_path.exists() {
        std::fs::write(&entry_path, b"")
            .with_context(|| format!("create placeholder {}", entry_path.display()))?;
    }

    Ok(())
}

pub fn service_build(octon_dir: &Path, category: &str, name: &str) -> anyhow::Result<()> {
    validate_ident(category)?;
    validate_ident(name)?;

    let service_dir = octon_dir
        .join("capabilities")
        .join("runtime")
        .join("services")
        .join(category)
        .join(name);
    let rust_dir = service_dir.join("rust");
    let build_target_dir = octon_dir
        .join("capabilities")
        .join("runtime")
        .join("services")
        .join("_ops")
        .join("state")
        .join("build")
        .join(format!("{category}-{name}-target"));

    // Best-effort prefetch for target-specific crates so offline builds work on cold CI runners.
    // If the fetch fails (for example, in a fully offline environment), we still proceed with
    // the offline build and rely on prewarmed caches.
    let fetch_status = std::process::Command::new("cargo")
        .arg("fetch")
        .arg("--locked")
        .arg("--target")
        .arg("wasm32-wasip1")
        .current_dir(&rust_dir)
        .status();
    if let Ok(status) = fetch_status {
        if !status.success() {
            eprintln!(
                "warning: cargo fetch --target wasm32-wasip1 failed; continuing with offline build"
            );
        }
    }

    // Run cargo-component.
    let status = std::process::Command::new("cargo")
        .arg("component")
        .arg("build")
        .arg("--release")
        // The Octon harness is expected to support offline execution.
        .arg("--offline")
        .env("CARGO_TARGET_DIR", &build_target_dir)
        .current_dir(&rust_dir)
        .status()
        .with_context(|| "failed to run 'cargo component build --release' (is cargo-component installed?)")?;

    if !status.success() {
        anyhow::bail!("cargo component build failed");
    }

    // Find the newest .wasm artifact under the configured CARGO_TARGET_DIR.
    let target_dir = build_target_dir;
    let mut newest: Option<(std::time::SystemTime, PathBuf)> = None;
    for entry in WalkDir::new(&target_dir)
        .follow_links(false)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if !entry.file_type().is_file() {
            continue;
        }
        if entry.path().extension().and_then(|e| e.to_str()) != Some("wasm") {
            continue;
        }
        let md = std::fs::metadata(entry.path())?;
        let mtime = md.modified().unwrap_or(std::time::UNIX_EPOCH);
        if newest.as_ref().map(|(t, _)| mtime > *t).unwrap_or(true) {
            newest = Some((mtime, entry.path().to_path_buf()));
        }
    }

    let (_, wasm_path) = newest.ok_or_else(|| {
        anyhow::anyhow!("no .wasm artifact found under {}", target_dir.display())
    })?;

    let wasm_bytes = std::fs::read(&wasm_path)
        .with_context(|| format!("read wasm artifact {}", wasm_path.display()))?;

    // Copy to service.wasm (atomic write).
    let entry_dest = service_dir.join("service.wasm");
    atomic_write(&entry_dest, &wasm_bytes)?;

    // Compute sha256 and update service.json integrity.
    let sha = hex::encode(Sha256::digest(&wasm_bytes));

    let service_json_path = service_dir.join("service.json");
    let mut manifest: serde_json::Value = serde_json::from_slice(&std::fs::read(&service_json_path)?)?;
    manifest["integrity"] = serde_json::json!({"wasm_sha256": sha});

    atomic_write(&service_json_path, &serde_json::to_vec_pretty(&manifest)?)?;

    Ok(())
}

fn validate_ident(s: &str) -> anyhow::Result<()> {
    let bytes = s.as_bytes();
    if bytes.is_empty() {
        anyhow::bail!("identifier is empty");
    }
    if !(bytes[0] as char).is_ascii_lowercase() {
        anyhow::bail!("identifier must start with a lowercase letter");
    }
    if bytes.len() > 64 {
        anyhow::bail!("identifier too long");
    }
    for &b in bytes {
        let c = b as char;
        let ok = c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-';
        if !ok {
            anyhow::bail!("identifier contains invalid character '{c}'");
        }
    }
    Ok(())
}

fn atomic_write(path: &Path, data: &[u8]) -> anyhow::Result<()> {
    let dir = path.parent().ok_or_else(|| anyhow::anyhow!("missing parent dir"))?;
    std::fs::create_dir_all(dir)?;

    let tmp = path.with_file_name(format!(
        "{}.tmp.{}",
        path.file_name().and_then(|s| s.to_str()).unwrap_or("file"),
        std::process::id()
    ));

    {
        use std::io::Write;
        let mut f = std::fs::File::create(&tmp)?;
        f.write_all(data)?;
        f.sync_all()?;
    }

    #[cfg(windows)]
    {
        if path.exists() {
            std::fs::remove_file(path)?;
        }
    }

    std::fs::rename(&tmp, path)?;
    Ok(())
}
