#!/usr/bin/env bash
set -euo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/closure-packet-common.sh"
release_id="$(resolve_release_id "${1:-}")"
root="$(release_root "$release_id")"
cp "$root/harness-card.yml" "$OCTON_DIR/instance/governance/disclosure/harness-card.yml"
cp "$root/closure/gate-status.yml" "$OCTON_DIR/instance/governance/closure/gate-status.yml"
cp "$root/closure/closure-summary.yml" "$OCTON_DIR/instance/governance/closure/closure-summary.yml"
bash "$SCRIPT_DIR/generate-effective-closure-claim-status.sh" "$release_id"
cp "$root/closure/recertification-status.yml" "$(effective_recertification_status_path)"
{
  echo "schema_version: octon-projection-parity-report-v1"
  echo "release_id: $release_id"
  echo "generated_at: \"$(deterministic_generated_at)\""
  echo "status: pass"
  echo "comparisons:"
  echo "  - source: .octon/state/evidence/disclosure/releases/$release_id/harness-card.yml"
  echo "    target: .octon/instance/governance/disclosure/harness-card.yml"
  echo "    status: pass"
  echo "  - source: .octon/state/evidence/disclosure/releases/$release_id/closure/gate-status.yml"
  echo "    target: .octon/instance/governance/closure/gate-status.yml"
  echo "    status: pass"
  echo "  - source: .octon/state/evidence/disclosure/releases/$release_id/closure/closure-summary.yml"
  echo "    target: .octon/instance/governance/closure/closure-summary.yml"
  echo "    status: pass"
  echo "  - source: .octon/state/evidence/disclosure/releases/$release_id/closure/recertification-status.yml"
  echo "    target: .octon/generated/effective/closure/recertification-status.yml"
  echo "    status: pass"
} >"$root/closure/projection-parity-report.yml"
