#!/usr/bin/env bash
set -euo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/closure-packet-common.sh"
release_id="$(resolve_release_id "${1:-}")"
out="$(release_root "$release_id")/harness-card.yml"
mkdir -p "$(dirname "$out")"
{
  echo "schema_version: harness-card-v2"
  echo "card_id: hc-target-state-closure-$release_id"
  echo "claim_kind: release"
  echo "claim_status: complete"
  echo "claim_summary: >-"
  echo "  Octon's closure claim is provable across its admitted bounded support universe"
  echo "  because release disclosure, support claims, and exemplar run evidence are"
  echo "  regenerated from canonical repo surfaces and dual-pass certification."
  echo "support_target_ref: .octon/instance/governance/support-targets.yml"
  echo "governance_exclusions_ref: .octon/instance/governance/exclusions/action-classes.yml"
  echo "support_universe:"
  echo "  model_classes:"
  echo "    - repo-local-governed"
  echo "  workload_classes:"
  echo "    - observe-and-read"
  echo "    - repo-consequential"
  echo "  context_classes:"
  echo "    - reference-owned"
  echo "  locale_classes:"
  echo "    - english-primary"
  echo "retained_adapters:"
  echo "  host_adapters:"
  echo "    - repo-shell"
  echo "  model_adapters:"
  echo "    - repo-local-governed"
  echo "capability_packs:"
  echo "  - repo"
  echo "  - git"
  echo "  - shell"
  echo "  - telemetry"
  echo "coverage_ledger_ref: .octon/state/evidence/disclosure/releases/$release_id/closure/support-universe-coverage.yml"
  echo "proof_bundle_refs:"
  echo "  - .octon/framework/constitution/claim-truth-conditions.yml"
  echo "  - .octon/instance/governance/disclosure/release-lineage.yml"
  echo "  - .octon/instance/governance/closure/unified-execution-constitution.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/gate-status.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/closure-summary.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/closure-certificate.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/support-universe-coverage.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/proof-plane-coverage.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/cross-artifact-consistency.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/claim-drift-report.yml"
  echo "  - .octon/state/evidence/disclosure/releases/$release_id/closure/projection-parity-report.yml"
  while IFS= read -r run_id; do
    echo "  - .octon/state/evidence/disclosure/runs/$run_id/run-card.yml"
  done < <(representative_run_ids)
  echo "known_limits:"
  echo "  - Frontier-governed execution remains stage-only and excluded from the live claim."
  echo "  - Browser and API packs remain stage-only and excluded from the live claim."
  echo "  - GitHub, CI, and Studio host adapters remain projection-only and stage-only outside the live claim."
  echo "generated_at: \"$(deterministic_generated_at)\""
} >"$out"
