#!/usr/bin/env bash
set -euo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/closure-packet-common.sh"
release_id="$(resolve_release_id "${1:-}")"
root="$(release_root "$release_id")"
mkdir -p "$root/closure"
bash "$SCRIPT_DIR/generate-harness-card.sh" "$release_id"
bash "$SCRIPT_DIR/generate-closure-bundle.sh" "$release_id"
manifest="$root/manifest.yml"
{
  echo "schema_version: octon-release-bundle-manifest-v1"
  echo "release_id: $release_id"
  echo "generated_at: \"$(deterministic_generated_at)\""
  echo "generator_versions:"
  echo "  release_bundle: 1"
  echo "  harness_card: 1"
  echo "  closure_bundle: 1"
  echo "validator_versions:"
  echo "  evidence_classification: 1"
  echo "  cross_artifact: 1"
  echo "  wording: 1"
  echo "authored_input_digests:"
  echo "  charter: $(sha256_file "$OCTON_DIR/framework/constitution/charter.yml")"
  echo "  support_targets: $(sha256_file "$OCTON_DIR/instance/governance/support-targets.yml")"
  echo "  workspace_charter: $(sha256_file "$OCTON_DIR/instance/charter/workspace.yml")"
  echo "proof_bundle_runs:"
  while IFS= read -r run_id; do
    echo "  - run://$run_id"
  done < <(representative_run_ids)
  echo "bundle_contents:"
  echo "  - harness-card.yml"
  echo "  - closure/gate-status.yml"
  echo "  - closure/closure-summary.yml"
  echo "  - closure/closure-certificate.yml"
  echo "  - closure/support-universe-coverage.yml"
  echo "  - closure/proof-plane-coverage.yml"
  echo "  - closure/cross-artifact-consistency.yml"
  echo "  - closure/claim-drift-report.yml"
  echo "  - closure/projection-parity-report.yml"
} >"$manifest"
