// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_invoke_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
    let result2 = T::invoke(_rt::string_lift(bytes0), _rt::string_lift(bytes1));
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec4 = (result2.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_invoke<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    /// Generic op dispatcher.
    /// `input-json` and return value are UTF-8 JSON strings.
    fn invoke(op: _rt::String, input_json: _rt::String) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_octon_service_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "invoke")] unsafe extern "C" fn
        export_invoke(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_invoke_cabi::<$ty > (arg0, arg1,
        arg2, arg3) } } #[unsafe (export_name = "cabi_post_invoke")] unsafe extern "C" fn
        _post_return_invoke(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_invoke::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_octon_service_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
/// Host logging (capability-gated by the kernel).
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod log {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    #[allow(unused_unsafe, clippy::all)]
    pub fn write(level: &str, message: &str) -> () {
        unsafe {
            let vec0 = level;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = message;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "log")]
            unsafe extern "C" {
                #[link_name = "write"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
            ) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1) };
        }
    }
}
/// Host clock (capability-gated by the kernel).
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod clock {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    #[allow(unused_unsafe, clippy::all)]
    pub fn now_ms() -> u64 {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "clock")]
            unsafe extern "C" {
                #[link_name = "now-ms"]
                fn wit_import0() -> i64;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0() -> i64 {
                unreachable!()
            }
            let ret = unsafe { wit_import0() };
            ret as u64
        }
    }
}
/// Host KV (capability-gated by the kernel).
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod kv {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    use super::_rt;
    #[allow(unused_unsafe, clippy::all)]
    pub fn get(key: &str) -> Option<_rt::String> {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 3
                    * ::core::mem::size_of::<*const u8>()],
            );
            let vec0 = key;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "kv")]
            unsafe extern "C" {
                #[link_name = "get"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result7 = match l3 {
                0 => None,
                1 => {
                    let e = {
                        let l4 = *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l5 = *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                        _rt::string_lift(bytes6)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            };
            result7
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn put(key: &str, value: &str) -> () {
        unsafe {
            let vec0 = key;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = value;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "kv")]
            unsafe extern "C" {
                #[link_name = "put"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
            ) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn del(key: &str) -> () {
        unsafe {
            let vec0 = key;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "kv")]
            unsafe extern "C" {
                #[link_name = "del"]
                fn wit_import1(_: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                unreachable!()
            }
            unsafe { wit_import1(ptr0.cast_mut(), len0) };
        }
    }
}
/// Host filesystem (capability-gated by the kernel, sandboxed to repo root).
/// See rust-fs-host-api.md for implementation details.
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod fs {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    use super::_rt;
    /// metadata
    #[derive(Clone, Copy)]
    pub enum NodeKind {
        File,
        Dir,
    }
    impl ::core::fmt::Debug for NodeKind {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
                NodeKind::File => f.debug_tuple("NodeKind::File").finish(),
                NodeKind::Dir => f.debug_tuple("NodeKind::Dir").finish(),
            }
        }
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct Stat {
        pub kind: NodeKind,
        pub size: u64,
        pub modified_ms: Option<u64>,
    }
    impl ::core::fmt::Debug for Stat {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Stat")
                .field("kind", &self.kind)
                .field("size", &self.size)
                .field("modified-ms", &self.modified_ms)
                .finish()
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// bytes
    pub fn read(path: &str) -> _rt::Vec<u8> {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 2
                    * ::core::mem::size_of::<*const u8>()],
            );
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "read"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
            let l3 = *ptr1.add(0).cast::<*mut u8>();
            let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len5 = l4;
            let result6 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
            result6
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn write(path: &str, data: &[u8]) -> () {
        unsafe {
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = data;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "write"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
            ) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// text (UTF-8)
    pub fn read_text(path: &str) -> _rt::String {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 2
                    * ::core::mem::size_of::<*const u8>()],
            );
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "read-text"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
            let l3 = *ptr1.add(0).cast::<*mut u8>();
            let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len5 = l4;
            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
            let result6 = _rt::string_lift(bytes5);
            result6
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn write_text(path: &str, data: &str) -> () {
        unsafe {
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = data;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "write-text"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
            ) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// queries
    pub fn exists(path: &str) -> bool {
        unsafe {
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "exists"]
                fn wit_import1(_: *mut u8, _: usize) -> i32;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) -> i32 {
                unreachable!()
            }
            let ret = unsafe { wit_import1(ptr0.cast_mut(), len0) };
            _rt::bool_lift(ret as u8)
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn list_dir(path: &str) -> _rt::Vec<_rt::String> {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 2
                    * ::core::mem::size_of::<*const u8>()],
            );
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "list-dir"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
            let l3 = *ptr1.add(0).cast::<*mut u8>();
            let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base8 = l3;
            let len8 = l4;
            let mut result8 = _rt::Vec::with_capacity(len8);
            for i in 0..len8 {
                let base = base8.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                let e8 = {
                    let l5 = *base.add(0).cast::<*mut u8>();
                    let l6 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len7 = l6;
                    let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                    _rt::string_lift(bytes7)
                };
                result8.push(e8);
            }
            _rt::cabi_dealloc(
                base8,
                len8 * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result9 = result8;
            result9
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn glob(pattern: &str) -> _rt::Vec<_rt::String> {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 2
                    * ::core::mem::size_of::<*const u8>()],
            );
            let vec0 = pattern;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "glob"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
            let l3 = *ptr1.add(0).cast::<*mut u8>();
            let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base8 = l3;
            let len8 = l4;
            let mut result8 = _rt::Vec::with_capacity(len8);
            for i in 0..len8 {
                let base = base8.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                let e8 = {
                    let l5 = *base.add(0).cast::<*mut u8>();
                    let l6 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len7 = l6;
                    let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                    _rt::string_lift(bytes7)
                };
                result8.push(e8);
            }
            _rt::cabi_dealloc(
                base8,
                len8 * (2 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result9 = result8;
            result9
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    /// mutations
    pub fn mkdirp(path: &str) -> () {
        unsafe {
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "mkdirp"]
                fn wit_import1(_: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                unreachable!()
            }
            unsafe { wit_import1(ptr0.cast_mut(), len0) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn remove_file(path: &str) -> () {
        unsafe {
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "remove-file"]
                fn wit_import1(_: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                unreachable!()
            }
            unsafe { wit_import1(ptr0.cast_mut(), len0) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn remove_dir_recursive(path: &str) -> () {
        unsafe {
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "remove-dir-recursive"]
                fn wit_import1(_: *mut u8, _: usize);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                unreachable!()
            }
            unsafe { wit_import1(ptr0.cast_mut(), len0) };
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn get_stat(path: &str) -> Option<Stat> {
        unsafe {
            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit<u8>; 40]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 40]);
            let vec0 = path;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "fs")]
            unsafe extern "C" {
                #[link_name = "get-stat"]
                fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                unreachable!()
            }
            unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result9 = match l3 {
                0 => None,
                1 => {
                    let e = {
                        let l4 = i32::from(*ptr1.add(8).cast::<u8>());
                        let v5 = match l4 {
                            0 => NodeKind::File,
                            n => {
                                debug_assert_eq!(n, 1, "invalid enum discriminant");
                                NodeKind::Dir
                            }
                        };
                        let l6 = *ptr1.add(16).cast::<i64>();
                        let l7 = i32::from(*ptr1.add(24).cast::<u8>());
                        Stat {
                            kind: v5,
                            size: l6 as u64,
                            modified_ms: match l7 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l8 = *ptr1.add(32).cast::<i64>();
                                        l8 as u64
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        }
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            };
            result9
        }
    }
}
/// Host HTTP client (capability-gated by the kernel).
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod http {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() = super::__link_custom_section_describing_imports;
    use super::_rt;
    #[derive(Clone)]
    pub struct Header {
        pub name: _rt::String,
        pub value: _rt::String,
    }
    impl ::core::fmt::Debug for Header {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Header")
                .field("name", &self.name)
                .field("value", &self.value)
                .finish()
        }
    }
    #[derive(Clone)]
    pub struct Request {
        pub method: _rt::String,
        pub url: _rt::String,
        pub headers: _rt::Vec<Header>,
        pub body: _rt::Vec<u8>,
        pub timeout_ms: Option<u64>,
    }
    impl ::core::fmt::Debug for Request {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Request")
                .field("method", &self.method)
                .field("url", &self.url)
                .field("headers", &self.headers)
                .field("body", &self.body)
                .field("timeout-ms", &self.timeout_ms)
                .finish()
        }
    }
    #[derive(Clone)]
    pub struct Response {
        pub status: u16,
        pub headers: _rt::Vec<Header>,
        pub body: _rt::Vec<u8>,
    }
    impl ::core::fmt::Debug for Response {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Response")
                .field("status", &self.status)
                .field("headers", &self.headers)
                .field("body", &self.body)
                .finish()
        }
    }
    #[allow(unused_unsafe, clippy::all)]
    pub fn send(req: &Request) -> Response {
        unsafe {
            #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
            #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
            struct RetArea(
                [::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()],
            );
            let mut ret_area = RetArea(
                [::core::mem::MaybeUninit::uninit(); 5
                    * ::core::mem::size_of::<*const u8>()],
            );
            let Request {
                method: method0,
                url: url0,
                headers: headers0,
                body: body0,
                timeout_ms: timeout_ms0,
            } = req;
            let vec1 = method0;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let vec2 = url0;
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            let vec6 = headers0;
            let len6 = vec6.len();
            let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                vec6.len() * (4 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result6 = if layout6.size() != 0 {
                let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout6);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec6.into_iter().enumerate() {
                let base = result6.add(i * (4 * ::core::mem::size_of::<*const u8>()));
                {
                    let Header { name: name3, value: value3 } = e;
                    let vec4 = name3;
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = value3;
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                }
            }
            let vec7 = body0;
            let ptr7 = vec7.as_ptr().cast::<u8>();
            let len7 = vec7.len();
            let (result8_0, result8_1) = match timeout_ms0 {
                Some(e) => (1i32, _rt::as_i64(e)),
                None => (0i32, 0i64),
            };
            let ptr9 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "http")]
            unsafe extern "C" {
                #[link_name = "send"]
                fn wit_import10(
                    _: *mut u8,
                    _: usize,
                    _: *mut u8,
                    _: usize,
                    _: *mut u8,
                    _: usize,
                    _: *mut u8,
                    _: usize,
                    _: i32,
                    _: i64,
                    _: *mut u8,
                );
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import10(
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
                _: i32,
                _: i64,
                _: *mut u8,
            ) {
                unreachable!()
            }
            unsafe {
                wit_import10(
                    ptr1.cast_mut(),
                    len1,
                    ptr2.cast_mut(),
                    len2,
                    result6,
                    len6,
                    ptr7.cast_mut(),
                    len7,
                    result8_0,
                    result8_1,
                    ptr9,
                )
            };
            let l11 = i32::from(*ptr9.add(0).cast::<u16>());
            let l12 = *ptr9.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l13 = *ptr9.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base20 = l12;
            let len20 = l13;
            let mut result20 = _rt::Vec::with_capacity(len20);
            for i in 0..len20 {
                let base = base20.add(i * (4 * ::core::mem::size_of::<*const u8>()));
                let e20 = {
                    let l14 = *base.add(0).cast::<*mut u8>();
                    let l15 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len16 = l15;
                    let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
                    let l17 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l18 = *base
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len19 = l18;
                    let bytes19 = _rt::Vec::from_raw_parts(l17.cast(), len19, len19);
                    Header {
                        name: _rt::string_lift(bytes16),
                        value: _rt::string_lift(bytes19),
                    }
                };
                result20.push(e20);
            }
            _rt::cabi_dealloc(
                base20,
                len20 * (4 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let l21 = *ptr9
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l22 = *ptr9.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len23 = l22;
            let result24 = Response {
                status: l11 as u16,
                headers: result20,
                body: _rt::Vec::from_raw_parts(l21.cast(), len23, len23),
            };
            if layout6.size() != 0 {
                _rt::alloc::dealloc(result6.cast(), layout6);
            }
            result24
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_octon_service_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_octon_service_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_octon_service_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:octon:runtime@1.0.0:octon-service:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 868] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe0\x05\x01A\x02\x01\
A\x0c\x01B\x02\x01@\x02\x05levels\x07messages\x01\0\x04\0\x05write\x01\0\x03\0\x03\
log\x05\0\x01B\x02\x01@\0\0w\x04\0\x06now-ms\x01\0\x03\0\x05clock\x05\x01\x01B\x07\
\x01ks\x01@\x01\x03keys\0\0\x04\0\x03get\x01\x01\x01@\x02\x03keys\x05values\x01\0\
\x04\0\x03put\x01\x02\x01@\x01\x03keys\x01\0\x04\0\x03del\x01\x03\x03\0\x02kv\x05\
\x02\x01B\x1c\x01q\x02\x04file\0\0\x03dir\0\0\x04\0\x09node-kind\x03\0\0\x01kw\x01\
r\x03\x04kind\x01\x04sizew\x0bmodified-ms\x02\x04\0\x04stat\x03\0\x03\x01p}\x01@\
\x01\x04paths\0\x05\x04\0\x04read\x01\x06\x01@\x02\x04paths\x04data\x05\x01\0\x04\
\0\x05write\x01\x07\x01@\x01\x04paths\0s\x04\0\x09read-text\x01\x08\x01@\x02\x04\
paths\x04datas\x01\0\x04\0\x0awrite-text\x01\x09\x01@\x01\x04paths\0\x7f\x04\0\x06\
exists\x01\x0a\x01ps\x01@\x01\x04paths\0\x0b\x04\0\x08list-dir\x01\x0c\x01@\x01\x07\
patterns\0\x0b\x04\0\x04glob\x01\x0d\x01@\x01\x04paths\x01\0\x04\0\x06mkdirp\x01\
\x0e\x04\0\x0bremove-file\x01\x0e\x04\0\x14remove-dir-recursive\x01\x0e\x01k\x04\
\x01@\x01\x04paths\0\x0f\x04\0\x08get-stat\x01\x10\x03\0\x02fs\x05\x03\x01B\x0b\x01\
r\x02\x04names\x05values\x04\0\x06header\x03\0\0\x01p\x01\x01p}\x01kw\x01r\x05\x06\
methods\x03urls\x07headers\x02\x04body\x03\x0atimeout-ms\x04\x04\0\x07request\x03\
\0\x05\x01r\x03\x06status{\x07headers\x02\x04body\x03\x04\0\x08response\x03\0\x07\
\x01@\x01\x03req\x06\0\x08\x04\0\x04send\x01\x09\x03\0\x04http\x05\x04\x01@\x02\x02\
ops\x0ainput-jsons\0s\x04\0\x06invoke\x01\x05\x04\0!octon:runtime/octon-service@\
1.0.0\x04\0\x0b\x13\x01\0\x0docton-service\x03\0\0\0G\x09producers\x01\x0cproces\
sed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
