#!/bin/bash
# ARE Loop Initialization Script
# Creates the tracking infrastructure for a documentation improvement workflow
#
# Usage: are-init.sh <target-directory>
#
# This script creates a .harmony/.are/ directory structure in the specified
# target documentation directory. The target directory should be the root of
# the documentation set you want to improve (e.g., docs/harmony/ai/methodology/).
#
# Generated artifacts will be placed in: <target-directory>/.harmony/.are/
# ARE prompts are located centrally in: .harmony/orchestration/workflows/are/

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the directory where this script lives (for referencing ARE prompts)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${GREEN}ARE Loop Initialization${NC}"
echo "========================"
echo ""

# Check for target directory argument
if [ -z "$1" ]; then
    echo -e "${YELLOW}Usage:${NC} are-init.sh <target-directory>"
    echo ""
    echo "  <target-directory>  Path to the documentation directory to improve"
    echo "                      (e.g., docs/harmony/ai/methodology/)"
    echo ""
    echo "  Generated artifacts will be placed in: <target-directory>/.harmony/.are/"
    echo ""
    read -p "Enter target directory path: " TARGET_DIR
    if [ -z "$TARGET_DIR" ]; then
        echo -e "${RED}Error: No target directory specified${NC}"
        exit 1
    fi
else
    TARGET_DIR="$1"
fi

# Resolve to absolute path
TARGET_DIR="$(cd "$TARGET_DIR" 2>/dev/null && pwd)" || {
    echo -e "${RED}Error: Target directory does not exist: $1${NC}"
    exit 1
}

echo -e "Target documentation directory: ${BLUE}$TARGET_DIR${NC}"
echo ""

# Define the ARE directory path
ARE_DIR="$TARGET_DIR/.harmony/.are"

# Check if .harmony/.are directory already exists
if [ -d "$ARE_DIR" ]; then
    echo -e "${YELLOW}Warning: .harmony/.are directory already exists in target${NC}"
    read -p "Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 1
    fi
    rm -rf "$ARE_DIR"
fi

# Create .harmony directory if it doesn't exist
if [ ! -d "$TARGET_DIR/.harmony" ]; then
    echo -e "Creating ${BLUE}.harmony/${NC} directory in target..."
    mkdir -p "$TARGET_DIR/.harmony"

    # Create a minimal .harmony README for context
    cat > "$TARGET_DIR/.harmony/README.md" << 'EOF'
# .harmony

This directory contains workspace-specific files for AI agent workflows.

## Structure

- `.are/` - ARE Loop tracking artifacts for documentation improvement

## Note

This `.harmony` was auto-generated by `are-init.sh`. You may want to add
additional workspace files as needed for your documentation workflow.
EOF
fi

# Create directory structure
echo -e "Creating ${BLUE}.harmony/.are/${NC} directory structure..."
mkdir -p "$ARE_DIR/artifacts"

# Get parameters
echo ""
read -p "Concept/Topic (e.g., security, onboarding, API usage): " CONCEPT
read -p "ARE Tier (ARE-Lite/ARE-Standard/ARE-Full) [ARE-Standard]: " TIER
TIER=${TIER:-ARE-Standard}
read -p "Documentation scope description: " SCOPE

# Collect document paths
echo ""
echo "Enter document paths (one per line, empty line to finish):"
echo -e "${YELLOW}Note: Paths can be relative to target directory or absolute${NC}"
DOCS=()
while true; do
    read -p "  Path: " doc_path
    if [ -z "$doc_path" ]; then
        break
    fi
    
    # Try to resolve the path
    if [ -f "$doc_path" ]; then
        # Absolute or already valid relative path
        DOCS+=("$doc_path")
        echo -e "    ${GREEN}✓${NC} Added: $doc_path"
    elif [ -f "$TARGET_DIR/$doc_path" ]; then
        # Relative to target directory
        DOCS+=("$doc_path")
        echo -e "    ${GREEN}✓${NC} Added: $doc_path"
    else
        echo -e "    ${RED}✗${NC} File not found: $doc_path"
    fi
done

if [ ${#DOCS[@]} -eq 0 ]; then
    echo -e "${RED}Error: No documents specified${NC}"
    exit 1
fi

# Get current timestamp
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Calculate relative path from target to repo root (for referencing ARE prompts)
# This helps agents find the central ARE prompts
REPO_ROOT="$(git -C "$TARGET_DIR" rev-parse --show-toplevel 2>/dev/null)" || REPO_ROOT=""
if [ -n "$REPO_ROOT" ]; then
    ARE_PROMPTS_PATH=".harmony/orchestration/workflows/are"
else
    ARE_PROMPTS_PATH="$SCRIPT_DIR"
fi

# Create are-config.json
echo ""
echo "Creating are-config.json..."
cat > "$ARE_DIR/are-config.json" << EOF
{
  "concept": "$CONCEPT",
  "tier": "$TIER",
  "scope": "$SCOPE",
  "targetDirectory": "$TARGET_DIR",
  "initialized": "$TIMESTAMP",
  "arePromptsPath": "$ARE_PROMPTS_PATH",
  "documents": [
$(printf '    "%s"' "${DOCS[0]}")
$(for doc in "${DOCS[@]:1}"; do printf ',\n    "%s"' "$doc"; done)
  ]
}
EOF

# Create are-progress.json
echo "Creating are-progress.json..."
cat > "$ARE_DIR/are-progress.json" << EOF
{
  "meta": {
    "concept": "$CONCEPT",
    "tier": "$TIER",
    "targetDirectory": "$TARGET_DIR",
    "started": "$TIMESTAMP",
    "lastUpdated": "$TIMESTAMP",
    "totalDocuments": ${#DOCS[@]},
    "completedDocuments": 0
  },
  "documents": [
EOF

# Add each document to progress
priority=1
for i in "${!DOCS[@]}"; do
    doc="${DOCS[$i]}"
    doc_id=$(basename "$doc" .md | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    
    if [ $i -eq $((${#DOCS[@]} - 1)) ]; then
        comma=""
    else
        comma=","
    fi
    
    cat >> "$ARE_DIR/are-progress.json" << EOF
    {
      "id": "$doc_id",
      "path": "$doc",
      "priority": $priority,
      "status": "pending",
      "cycles": []
    }$comma
EOF
    ((priority++))
done

cat >> "$ARE_DIR/are-progress.json" << EOF
  ],
  "setAnalysis": {
    "status": "pending",
    "terminologyIssues": null,
    "duplicationIssues": null,
    "crossRefIssues": null
  }
}
EOF

# Create are-session-log.md
echo "Creating are-session-log.md..."
cat > "$ARE_DIR/are-session-log.md" << EOF
# ARE Loop Session Log

## Workflow Configuration

| Field | Value |
|-------|-------|
| **Concept** | $CONCEPT |
| **Tier** | $TIER |
| **Scope** | $SCOPE |
| **Target Directory** | $TARGET_DIR |
| **Documents** | ${#DOCS[@]} |
| **Initialized** | $TIMESTAMP |

### Document List

| Priority | Document | Status |
|----------|----------|--------|
EOF

priority=1
for doc in "${DOCS[@]}"; do
    echo "| $priority | $doc | Pending |" >> "$ARE_DIR/are-session-log.md"
    ((priority++))
done

cat >> "$ARE_DIR/are-session-log.md" << EOF

---

## Session 1: Initialization

**Date**: $TIMESTAMP
**Type**: Setup

### Actions Completed

- Created \`.harmony/.are/\` directory structure
- Initialized tracking files
- Inventoried ${#DOCS[@]} documents

### Files Created

- \`.harmony/.are/are-config.json\` - Workflow configuration
- \`.harmony/.are/are-progress.json\` - Progress tracking
- \`.harmony/.are/are-session-log.md\` - Session history

### Next Session Should

1. Read \`.harmony/.are/are-progress.json\` to understand current state
2. If ${#DOCS[@]} > 3, run Document Set Analysis first
3. Otherwise, begin Analyze phase on highest-priority document
4. Use prompts from \`$ARE_PROMPTS_PATH/\` directory

### Prompts to Use

Central ARE prompts are located at: \`$ARE_PROMPTS_PATH/\`

- **Set Analysis**: \`are-document-sets.md\`
- **Analyze Phase**: \`01-are-analyze-single-doc.md\`
- **Refine Phase**: \`03-are-refine.md\`
- **Evaluate Phase**: \`04-are-evaluate.md\`
- **Agent Harness**: \`agent-harness.md\`
EOF

# Create .gitignore for artifacts (optional)
cat > "$ARE_DIR/.gitignore" << EOF
# Keep artifacts but ignore temp files
*.tmp
*.bak
EOF

echo ""
echo -e "${GREEN}Initialization Complete!${NC}"
echo ""
echo "Created in $TARGET_DIR/.harmony/.are/:"
echo "  are-config.json     - Workflow configuration"
echo "  are-progress.json   - Progress tracking (JSON)"
echo "  are-session-log.md  - Session history (Markdown)"
echo "  artifacts/          - Directory for analysis artifacts"
echo ""
echo -e "${BLUE}Central ARE Prompts:${NC} $ARE_PROMPTS_PATH/"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Review .harmony/.are/are-progress.json"
echo "  2. Commit: git add $TARGET_DIR/.harmony && git commit -m 'ARE Loop: Initialize tracking for $SCOPE ($CONCEPT)'"
echo "  3. Start first working session using agent-harness.md prompts"
echo ""
